### ISSUE TITLE
GitHub Actions workflow triggered on push to master branch of fork

### ISSUE THREAD

**Issue by camelid** [rust-lang/rustc-dev-guide#1085]
Workflow run is here: https://github.com/camelid/rustc-dev-guide/runs/2082979294

This is a bug and was introduced by the new GHA CI.

cc @JohnTitor

**Comment by JohnTitor** [comment]
I sometimes use my fork CI to check things before submitting a PR and Travis was also enabled on fork IIRC so it's intentional (actually, date-check is also enabled and I thought it was fine).
We can disable it individually from the fork's settings page but I'm fine with disabling it on workflow config if you all want.

**Comment by camelid** [comment]
> Travis was also enabled on fork IIRC

All I can say is that I never noticed CI running on my fork :)

> but I'm fine with disabling it on workflow config if you all want.

I would prefer that, yes. IME CI for the main repo usually isn't triggered for forked repos as well.

> (actually, date-check is also enabled and I thought it was fine).

Ah, date-check should be disabled for forks too. How should I do that?
