### ISSUE TITLE
Update MIR `Place` description

### ISSUE THREAD

**Issue by pierwill** [rust-lang/rustc-dev-guide#1387]
It looks like this is out-of-date, since [`Place`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/struct.Place.html) is a struct, not an enum.

https://github.com/rust-lang/rustc-dev-guide/blob/9d2081110a3e2bc5f1c95ebd830f92d6fe1c2942/src/mir/index.md#L238-L247

**Comment by tshepang** [comment]
@spastorino this is something you worked on... would update it, but am not familiar enough

**Comment by spastorino** [comment]
Yes `Place` was an enum and if I'm not wrong I've changed it a long while ago to be an struct. By looking at the source code is still a struct https://github.com/rust-lang/rust/blob/7e54847de328a7346c588720f616bf1fcdf609d5/compiler/rustc_middle/src/mir/syntax.rs#L792-L797 so we can update this section of the guide yeah.

**Comment by tshepang** [comment]
@spastorino is the description that follows still accurate

**Comment by spastorino** [comment]
It seems to me that things have changed a bit since I've last checked it. I don't think statics are handled through it, I'd change the more abstract `ProjectionElem` to `PlaceElem` and I don't think `Deref` is handled through it anymore neither. To be honest, I didn't check the code to say what I'm saying, I'm kind of playing by ear.

cc @oli-obk

**Comment by oli-obk** [comment]
other than that `Deref` still exists (it's in the process of being removed), everything you said is correct
