### ISSUE TITLE
"Diagnostics: reporting errors and lints"

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rustc-dev-guide#14]
We should talk first about:

- Guidelines for emitting errors
    - How to find an error code and add an extended error
    - Conventions are how the error should be formatted (lowercase letter, etc)
        - link or maybe just inline [the RFC with guidelines on how extended errors should look](https://github.com/rust-lang/rfcs/blob/master/text/1567-long-error-codes-explanation-normalization.md)
    - when to use `span_label` etc
- How to emit lints
    - When to use a lint
    - If you have a tcx
    - Before you have a tcx
    - Some tips here at the end of [Rustc bug fix procedure](https://forge.rust-lang.org/rustc-bug-fix-procedure.html)

EDIT(mark-i-m): See https://github.com/rust-lang/rustc-dev-guide/issues/14#issuecomment-514932385

cc @estebank

**Comment by Karrq** [comment]
Looks to me like this issue is currently missing the following:


Errors:
- How to find an error code and add an extended error
- Conventions are how the error should be formatted (lowercase letter, etc) 
- when to use `span_label` etc

Lints:
Nothing? Maybe the section about removing lints present in the [rustc Bug Fix Procedure](https://forge.rust-lang.org/rustc-bug-fix-procedure.html) could be added.

**Comment by phansch** [comment]
It might also be nice to link to the [lint naming recommendations](https://rust-lang.github.io/rfcs/0344-conventions-galore.html#lints) from RFC0344

**Comment by rylev** [comment]
Triage: closing. As we now have sections on diagnostics, this issue is a bit too general. I'm closing this in favor of more specific issues.
