### ISSUE TITLE
how to cite this guide ?

### ISSUE THREAD

**Issue by zapashcanon** [rust-lang/rustc-dev-guide#1534]
Hi,

I'm writing a research paper in which I'd like to cite a chapter of the guide. I've been coming up with the following bibtex entry:

```bibtex
@misc{Con18,
  title = "Guide to Rustc Development",
  author = {The Guide To Rustc Development Contributors},
  howpublished = "\url{https://rustc-dev-guide.rust-lang.org/backend/monomorph.html}",
  year = 2018,
  note = "Accessed: 2022-12-23"
}
```

The `Con18` is what have been autogenerated on the first rendering (it comes from the last word in the `author` part: `Contributors`) and is what is going to appear when the paper is cited in the document.

Is there a better list of authors somewhere ? What about including a bibtex entry somewhere in the guide so people don't have to do it each time ?

**Comment by JohnTitor** [comment]
We generally use the wording "The Rust Project Developers" or something else ("Contributors" also seems fine to me, but I'm not familiar with the citation much).
Since we have a lot of contributors, listing all the folks isn't realistic (or, listing folks involved in a particular page would be an alternative?).

Maybe it's good time to prepare the citation file on the repo: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

I'll take a look next week.

**Comment by JohnTitor** [comment]
An update from me: I couldn't make time to work on this last week. I'm going to revisit this after my vacation (hopefully next week), but feel free to beat me if someone is willing to do it :)

**Comment by JohnTitor** [comment]
Okay, I've opened https://github.com/rust-lang/rustc-dev-guide/pull/1550. Since I'm not familiar with citations, feel free to drop your thoughts there, it's definitely helpful!
