### ISSUE TITLE
Incremental build on Windows

### ISSUE THREAD

**Issue by hcs64** [rust-lang/rustc-dev-guide#187]
I've been trying the instructions at `how-to-build-and-run.md` with MSYS2 set up as in the main Rust readme, but at link time I get an "ordinal too large" error. I have been able to make more progress by removing the `-i` for incremental build from `./x.py build -i --stage 1 src/libstd`, this might be worth a brief mention.

(I'm not sure if that's the only change needed, I removed the `config.toml` customizations unsuccessfully before trying this route, I'll follow up once I can start another build from scratch.)

**Comment by mark-i-m** [comment]
@retep998 have you seen this error before? Any thoughts?

**Comment by retep998** [comment]
This is the first time I've heard about this specific issue. A similar issue I have seen is for `pc-windows-msvc` where people are running into `LINK : fatal error LNK1189: library limit of 65535 objects exceeded` because incremental and codegen units split up everything into so many object files that it exceeds limits in the linker. I don't know if they're the same issue, but it would be worth someone investigating the limits of both of those linkers.

**Comment by mark-i-m** [comment]
Hmm... Perhaps it would be good to open an issue on rust-lang/rust?

@hcs64 would you mind doing that and linking to this issue?

**Comment by hcs64** [comment]
There's already https://github.com/rust-lang/rust/issues/53014, so I'll just mention there it happens with pc-windows-gnu as well.

I'd brought it up here because this doc suggests `-i` and it'd have saved some time to avoid on Windows.

**Comment by mark-i-m** [comment]
Hmm i see what you mean. We should add a note with a link to this post where it suggests -i. Would you mind opening a PR?

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/issues/53014 has been closed - does this issue need to stay open? I think there are a fair number of compiler contributors using incremental on windows.

**Comment by rylev** [comment]
Going to close this because I've not heard of this issue. Windows with MSVC is my main driver and I've not run into issues. We can reopen if others have issues.
