### ISSUE TITLE
Document setup of rust-analyzer specifically for rustc hacking atop "popular" IDE/editors

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rustc-dev-guide#554]
I took an informal [poll](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/weekly.20meeting.202020-01-02.20.2354818/near/184657134) at the last compiler triage meeting to get an idea of what editors/IDEs the current set of rustc developers use to hack on rustc.

The reason I asked the question was that I wanted to know which environments we should aim to document decently in terms of "how do I set up rust-analyzer here", and, if necessary, "how do I make rust-analyzer work well with rustc here"

The answers:

 * vim: 6 (4 of whom already use rust-analyzer)
 * VS Code: 5 (3 of whom already use rust-analyzer)
 * emacs: 2
 * Sublime Text: 1
 * IntelliJ Rust: 1

I'm guessing there's no point in "integrating" rust-analyzer with IntelliJ Rust.

But the other four cases are worth documenting.

 * [ ] VS Code is the primary target for rust-analyzer, and so documenting that should be trivial
    *  (mostly, AFAICT, about how to properly open the rustc project so that the IDE knows where to look for the `Cargo.toml`.)
 * [ ] vim is the most popular editor so I guess it should get the most attention
   * matklad did warn me ahead of time that it may be difficult to document since there are multiple `lsp` extensions available for it.
 * [ ] I use emacs and I mess it up all the time so I will be happy to write down the concrete set up steps.
 * [ ] We'll see about Sublime Text

**Comment by pnkfelix** [comment]
Ah, [I had promised](https://zulip-archive.rust-lang.org/131828tcompiler/22121weeklymeeting2020010254818.html#184657587) at that same meeting to do the aforementioned survey via email, since I was worried that relying on the meeting alone was going to leave out contributors. I'll set up that survey next before I make any prioritization decisions based on the data above. (However, I feel pretty safe saying that we should, at minimum, document how to setup rust-analyzer/lsp integration with vim, vscode, and emacs.)

**Comment by spastorino** [comment]
https://github.com/prabirshrestha/vim-lsp seem to be one of the most popular ones. Maybe targeting just that one or two would suffice for vim?.

**Comment by mark-i-m** [comment]
I personally use neovim with `coc.nvim` + rust-analyzer.

**Comment by jyn514** [comment]
My ide experience with rustc has not been great. Setting any tool to run `x.py check` in the background completely breaks my build directory because x.py doesn't have build locks - cc @Mark-Simulacrum, maybe this is something that could be added? Until then though I'd be hesitant to recommend any extension that goes through cargo (notably RLS and rust_analyzer).

**Comment by mark-i-m** [comment]
I've never actually done that. I just run stock rust-analyzer without changing any settings at all, and it works fine.

**Comment by jyn514** [comment]
Stock rust-analyzer runs `cargo check` in the background AFAIK. Either that or there's something else breaking my build directory 👀

**Comment by mark-i-m** [comment]
Yep, that's my understanding as well, and yet somehow things just work... That said, I tend to mostly use rust-analyzer for completion and error messages; I don't use all of the extra IDE features, so perhaps there is something broken but I don't use it?

**Comment by jieyouxu** [comment]
Triage (in 2024): our setups have pretty much all converged on r-a, and editor setups on top of that are supported by `./x set $editor` in bootstrap (e.g. helix, vim/neovim, emacs) and can have examples in `src/etc/`. RustRover (from Jetbrains) doesn't really handle the r-l/r repo structure because it's slightly cursed and it doesn't use r-a, but yeah.

There is now plenty of info on https://rustc-dev-guide.rust-lang.org/building/suggested.html#configuring-rust-analyzer-for-rustc, so closing as completed.
